[workspace]
members = [
  "xtask",
  "crates/devicetree",
  "crates/sbi",
  "crates/riscv",
  "crates/log",
  "crates/kernel",
]

[profile.release]
debug = true
lto = "fat"
overflow-checks = true
debug-assertions = true
