[package]
name = "xtask"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.0.0-beta.2", default-features = false, features = ["std", "suggestions", "color"] }
xshell = "0.1"
